// Generated by SolidPython 1.1.3 on 2025-11-14 12:39:12


union() {
	cylinder(center = false, d = 80.0000000000, h = 2.0000000000);
	translate(v = [0, -11.4424242424, 2.0000000000]) {
		linear_extrude(height = 1.5000000000) {
			text(halign = "center", size = 8.4848484848, text = "CHRISTOPHER", valign = "center");
		}
	}
	translate(v = [-31.0406852248, -16.1742947987, 2.0000000000]) {
		cube(center = true, size = [1.9186295503, 0.6852248394, 1.5000000000]);
	}
	translate(v = [-28.7794432548, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [-26.5182012848, -16.1742947987, 2.0000000000]) {
		cube(center = true, size = [1.9186295503, 0.6852248394, 1.5000000000]);
	}
	translate(v = [-24.2569593148, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [-20.6937901499, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [-19.0492505353, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [-17.4047109208, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [-15.7601713062, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [-12.1970021413, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [-9.9357601713, -16.1742947987, 2.0000000000]) {
		cube(center = true, size = [1.9186295503, 0.6852248394, 1.5000000000]);
	}
	translate(v = [-7.6745182013, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [-4.1113490364, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [-2.4668094218, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [1.0963597430, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [2.7408993576, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [4.3854389722, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [8.5653104925, -16.1742947987, 2.0000000000]) {
		cube(center = true, size = [1.9186295503, 0.6852248394, 1.5000000000]);
	}
	translate(v = [13.3618843683, -16.1742947987, 2.0000000000]) {
		cube(center = true, size = [1.9186295503, 0.6852248394, 1.5000000000]);
	}
	translate(v = [16.2398286938, -16.1742947987, 2.0000000000]) {
		cube(center = true, size = [1.9186295503, 0.6852248394, 1.5000000000]);
	}
	translate(v = [19.1177730193, -16.1742947987, 2.0000000000]) {
		cube(center = true, size = [1.9186295503, 0.6852248394, 1.5000000000]);
	}
	translate(v = [23.2976445396, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [25.5588865096, -16.1742947987, 2.0000000000]) {
		cube(center = true, size = [1.9186295503, 0.6852248394, 1.5000000000]);
	}
	translate(v = [28.4368308351, -16.1742947987, 2.0000000000]) {
		cube(center = true, size = [1.9186295503, 0.6852248394, 1.5000000000]);
	}
	translate(v = [30.6980728051, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [34.2612419700, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [35.9057815846, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [37.5503211991, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [39.1948608137, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [42.7580299786, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [46.3211991435, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	translate(v = [48.5824411135, -16.1742947987, 2.0000000000]) {
		cube(center = true, size = [1.9186295503, 0.6852248394, 1.5000000000]);
	}
	translate(v = [50.8436830835, -16.1742947987, 2.0000000000]) {
		cylinder(d = 0.6852248394, h = 1.5000000000);
	}
	difference() {
		translate(v = [0, 36.0000000000, 1.0000000000]) {
			cylinder(d = 8, h = 2.0000000000);
		}
		translate(v = [0, 36.0000000000, 1.0000000000]) {
			cylinder(d = 4, h = 2.1000000000);
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
import argparse
from shapes import create_shape_with_text_and_morse
from morse import text_to_morse
from solid import scad_render_to_file

def parse_args():
    parser = argparse.ArgumentParser(description="Generate a 3D printable Christmas ornament with a name and its Morse code.")
    parser.add_argument("--shape", choices=["ball", "star", "bell"], required=True, help="Shape of the ornament.")
    parser.add_argument("--name", required=True, help="Name to place on ornament.")
    parser.add_argument("--size", type=float, default=80.0, help="Ornament diameter/width in mm (default: 80mm).")
    parser.add_argument("--thickness", type=float, default=2.0, help="Base thickness in mm (default: 2mm).")
    parser.add_argument("--text_height", type=float, default=1.5, help="Raised text height in mm (default: 1.5mm).")
    parser.add_argument("--morse_height", type=float, default=1.5, help="Raised Morse code height in mm (default: 1.5mm).")
    parser.add_argument("--morse_dot_size", type=float, default=2.5, help="Diameter of Morse dots in mm (default: 2.5mm).")
    parser.add_argument("--morse_dash_length", type=float, default=7.0, help="Length of Morse dashes in mm (default: 7mm).")
    parser.add_argument("--color_split", action="store_true", help="Include a thin separation layer under text/Morse for multicolor prints.")
    parser.add_argument("--add_loop", action="store_true", default=True, help="Add top attachment loop.")
    parser.add_argument("--output", default="ornament.stl", help="Output filename, default 'ornament.stl'.")
    return parser.parse_args()

def main():
    args = parse_args()
    morse = text_to_morse(args.name)
    print(f"Generating {args.shape} ornament with name '{args.name}' and Morse '{morse}'...")
    model = create_shape_with_text_and_morse(
        shape=args.shape,
        name=args.name,
        morse=morse,
        size=args.size,
        thickness=args.thickness,
        text_height=args.text_height,
        morse_height=args.morse_height,
        morse_dot_size=args.morse_dot_size,
        morse_dash_length=args.morse_dash_length,
        color_split=args.color_split,
        add_loop=args.add_loop
    )
    scad_filename = args.output.replace('.stl', '.scad')
    scad_render_to_file(model, scad_filename)
    print(f"Saved SCAD file as {scad_filename}")
    print("Open this file in OpenSCAD and export as STL after rendering.")

if __name__ == "__main__":
    main() 
 
************************************************/
