// Generated by SolidPython 1.1.3 on 2025-11-14 12:50:28


union() {
	cylinder(center = false, d = 80.0000000000, h = 2.0000000000);
	translate(v = [0, -4.7113973341, 2.0000000000]) {
		linear_extrude(height = 1.5000000000) {
			text(halign = "center", size = 7.2727272727, text = "CHRISTOPHER", valign = "center");
		}
	}
	translate(v = [-23.4464579901, -10.7272727273, 2.0000000000]) {
		cube(center = true, size = [1.1070840198, 0.3953871499, 1.5000000000]);
	}
	translate(v = [-22.1416803954, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-20.8369028007, -10.7272727273, 2.0000000000]) {
		cube(center = true, size = [1.1070840198, 0.3953871499, 1.5000000000]);
	}
	translate(v = [-19.5321252059, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-17.4761120264, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-16.5271828666, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-15.5782537068, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-14.6293245470, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-12.5733113674, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-11.2685337727, -10.7272727273, 2.0000000000]) {
		cube(center = true, size = [1.1070840198, 0.3953871499, 1.5000000000]);
	}
	translate(v = [-9.9637561779, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-7.9077429984, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-6.9588138386, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-4.9028006590, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-3.9538714992, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-3.0049423394, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [-0.5930807249, -10.7272727273, 2.0000000000]) {
		cube(center = true, size = [1.1070840198, 0.3953871499, 1.5000000000]);
	}
	translate(v = [2.1746293245, -10.7272727273, 2.0000000000]) {
		cube(center = true, size = [1.1070840198, 0.3953871499, 1.5000000000]);
	}
	translate(v = [3.8352553542, -10.7272727273, 2.0000000000]) {
		cube(center = true, size = [1.1070840198, 0.3953871499, 1.5000000000]);
	}
	translate(v = [5.4958813839, -10.7272727273, 2.0000000000]) {
		cube(center = true, size = [1.1070840198, 0.3953871499, 1.5000000000]);
	}
	translate(v = [7.9077429984, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [9.2125205931, -10.7272727273, 2.0000000000]) {
		cube(center = true, size = [1.1070840198, 0.3953871499, 1.5000000000]);
	}
	translate(v = [10.8731466227, -10.7272727273, 2.0000000000]) {
		cube(center = true, size = [1.1070840198, 0.3953871499, 1.5000000000]);
	}
	translate(v = [12.1779242175, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [14.2339373970, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [15.1828665568, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [16.1317957166, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [17.0807248764, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [19.1367380560, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [21.1927512356, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	translate(v = [22.4975288303, -10.7272727273, 2.0000000000]) {
		cube(center = true, size = [1.1070840198, 0.3953871499, 1.5000000000]);
	}
	translate(v = [23.8023064250, -10.7272727273, 2.0000000000]) {
		cylinder(d = 0.3953871499, h = 1.5000000000);
	}
	difference() {
		translate(v = [0, 44.0000000000, 1.0000000000]) {
			cylinder(d = 12, h = 2.0000000000);
		}
		translate(v = [0, 44.0000000000, 0.9500000000]) {
			cylinder(d = 8, h = 2.1000000000);
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
import argparse
from shapes import create_shape_with_text_and_morse
from morse import text_to_morse
from solid import scad_render_to_file

def parse_args():
    parser = argparse.ArgumentParser(description="Generate a 3D printable Christmas ornament with a name and its Morse code.")
    parser.add_argument("--shape", choices=["ball", "star", "bell"], required=True, help="Shape of the ornament.")
    parser.add_argument("--name", required=True, help="Name to place on ornament.")
    parser.add_argument("--size", type=float, default=80.0, help="Ornament diameter/width in mm (default: 80mm).")
    parser.add_argument("--thickness", type=float, default=2.0, help="Base thickness in mm (default: 2mm).")
    parser.add_argument("--text_height", type=float, default=1.5, help="Raised text height in mm (default: 1.5mm).")
    parser.add_argument("--morse_height", type=float, default=1.5, help="Raised Morse code height in mm (default: 1.5mm).")
    parser.add_argument("--morse_dot_size", type=float, default=2.5, help="Diameter of Morse dots in mm (default: 2.5mm).")
    parser.add_argument("--morse_dash_length", type=float, default=7.0, help="Length of Morse dashes in mm (default: 7mm).")
    parser.add_argument("--color_split", action="store_true", help="Include a thin separation layer under text/Morse for multicolor prints.")
    parser.add_argument("--add_loop", action="store_true", default=True, help="Add top attachment loop.")
    parser.add_argument("--output", default="ornament.stl", help="Output filename, default 'ornament.stl'.")
    return parser.parse_args()

def main():
    args = parse_args()
    morse = text_to_morse(args.name)
    print(f"Generating {args.shape} ornament with name '{args.name}' and Morse '{morse}'...")
    model = create_shape_with_text_and_morse(
        shape=args.shape,
        name=args.name,
        morse=morse,
        size=args.size,
        thickness=args.thickness,
        text_height=args.text_height,
        morse_height=args.morse_height,
        morse_dot_size=args.morse_dot_size,
        morse_dash_length=args.morse_dash_length,
        color_split=args.color_split,
        add_loop=args.add_loop
    )
    scad_filename = args.output.replace('.stl', '.scad')
    scad_render_to_file(model, scad_filename)
    print(f"Saved SCAD file as {scad_filename}")
    print("Open this file in OpenSCAD and export as STL after rendering.")

if __name__ == "__main__":
    main() 
 
************************************************/
